### ISSUE TITLE
Не запускается на ubuntu 16.04

### ISSUE THREAD

**Issue by shibormot** [aacidov/DisTypePro-desktop#2]
Сделал `npm install`.
Делаю `npm run dev` выдаёт ошибку синтаксиса:
```
i1@cashalot:~/src/aacidov/DisTypePro-desktop$ npm run dev

> distypepro@0.0.0 dev /home/i1/src/aacidov/DisTypePro-desktop
> node .electron-vue/dev-runner.js

/home/i1/src/aacidov/DisTypePro-desktop/.electron-vue/dev-runner.js:6
const { say } = require('cfonts')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

npm ERR! Linux 4.4.0-97-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! distypepro@0.0.0 dev: `node .electron-vue/dev-runner.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the distypepro@0.0.0 dev script 'node .electron-vue/dev-runner.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the distypepro package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node .electron-vue/dev-runner.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs distypepro
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls distypepro
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/i1/src/aacidov/DisTypePro-desktop/npm-debug.log
```

**Comment by shibormot** [comment]
То же самое и с `npm run build`:
```
i1@cashalot:~/src/aacidov/DisTypePro-desktop$ npm run build

> distypepro@0.0.0 build /home/i1/src/aacidov/DisTypePro-desktop
> node .electron-vue/build.js

/home/i1/src/aacidov/DisTypePro-desktop/.electron-vue/build.js:5
const { say } = require('cfonts')
      ^

SyntaxError: Unexpected token {
 
```

**Comment by ibakaidov** [comment]
Очень интересно... так как на маке всё работает, а ошибка явно про ES6/ES6

**Comment by shibormot** [comment]
ясно. посмотрю что у меня за node стоит

**Comment by AYeropudov** [comment]
npm ERR! node v4.2.6
обновите ноду до 6.11 в xenial доступно.
